#!/usr/bin/env bash
#
# `pnpm dev` — bring up the local Supabase stack, point the app at it, run
# migrations, then start Next. Everything here is idempotent, so re-running it
# after a reboot just reconnects.
#
# To use the remote database instead, run `pnpm dev:next` directly (and delete
# .env.development.local).

set -euo pipefail
cd "$(dirname "$0")/.."

SUPABASE=(pnpm exec supabase)
ENV_FILE=".env.development.local"

step() { printf '\033[1;36m→ %s\033[0m\n' "$1"; }
fail() { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# --- Docker ------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || fail "Docker isn't installed. Supabase's local stack needs it: https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || fail "Docker is installed but not running. Start Docker Desktop (or the daemon) and retry."

# --- Supabase project ------------------------------------------------------
if [ ! -f "supabase/config.toml" ]; then
  step "First run — scaffolding supabase/config.toml"
  "${SUPABASE[@]}" init
fi

# --- Start the stack (no-op if already up) --------------------------------
step "Starting local Supabase (first run pulls Docker images, ~1–2 min)"
"${SUPABASE[@]}" start || fail "supabase start failed. Try 'pnpm supabase stop --no-backup' then rerun."

# --- Wire the app to the local database -----------------------------------
DB_URL="$("${SUPABASE[@]}" status -o env 2>/dev/null | sed -n 's/^DB_URL="\(.*\)"$/\1/p')"
[ -n "$DB_URL" ] || fail "Couldn't read DB_URL from 'supabase status'."

cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev.sh — points the app at the local Supabase stack.
# Overrides .env.development. Delete this file to fall back to the remote DB.
DATABASE_URL="$DB_URL"
EOF
step "Wrote $ENV_FILE"

# --- Schema ---------------------------------------------------------------
step "Applying migrations"
pnpm db:migrate

STUDIO_URL="$("${SUPABASE[@]}" status -o env 2>/dev/null | sed -n 's/^STUDIO_URL="\(.*\)"$/\1/p')"
[ -n "$STUDIO_URL" ] && step "Supabase Studio: $STUDIO_URL"
step "Seed sample data any time with: pnpm db:seed"

# --- Next ---------------------------------------------------------------
step "Starting Next"
exec pnpm dev:next
